#!/bin/bash

# Mostrar los alias disponibles
echo "📌 Git Utils - Available Aliases:"
echo "                                                                         "
echo "🔹 gf     (git-fix)                -> Fixes issues with pull, merge, and rebase."
echo "🔹 gpa    (git-pull-all)           -> Pulls from all repositories."
echo "🔹 gpush  (git-push-all)           -> Pushes to all repositories."
echo "🔹 gtree  (git-tree)               -> Displays the commit history as a tree."
echo "🔹 ginfo  (git-info)               -> Shows this information."
echo "🔹 gp     (git-purge)              -> Uninstalls all Git utils and removes aliases."
echo "🔹 gca    (git-clone-all <user>)   -> Clones all public repositories from a GitHub user."
echo "🔹 gda    (git-delete-all)         -> Deletes all cloned git repositories."
echo "🔹 snvim  (set-nvim-raw)           -> Installs Neovim without plugins."
echo "🔹 snvimp (set-nvim-plugins)       -> Installs Neovim plugins and advanced configuration."
echo "🔹 snvima (set-nvim-all)           -> Installs Neovim and plugins."
echo "🔹 scde   (set-code-env)           -> Installs Neovim, plugins, and pulls from all repositories."
echo ""
echo "ℹ️  You can run any alias by simply typing it in the terminal."
echo "🚀  Happy coding!"
echo "Contact me at ismhernaismherna@student.42madrid.com"
