#!/bin/bash

# Mostrar los alias disponibles
echo "📌 Git Utils - Available Aliases:"
echo "                                                                         "
echo "🔹 gfix                           -> Fixes issues with pull, merge, and rebase."
echo "🔹 gpull                          -> Pulls from all repositories."
echo "🔹 gpush                          -> Pushes to all repositories."
echo "🔹 gtree                          -> Displays the commit history as a tree."
echo "🔹 ginfo                          -> Shows this information."
echo "🔹 gpurge                         -> Uninstalls all Git utils and removes aliases."
echo "🔹 gclone <user> <keyword>        -> Clones all public repositories from a GitHub user."
echo "🔹 gclean                         -> Deletes all cloned git repositories."
echo "🔹 snvim                          -> Installs Neovim without plugins."
echo "🔹 snvimp                         -> Installs Neovim plugins and advanced configuration."
echo "🔹 snvima                         -> Installs Neovim and plugins."
echo "🔹 scde                           -> Installs Neovim, plugins, and pulls from all repositories."
echo ""
echo "ℹ️  You can run any alias by simply typing it in the terminal."
echo "🚀  Happy coding!"
echo "Contact me at ismhernaismherna@student.42madrid.com"
