#!/bin/bash

# Mostrar los alias disponibles
echo "================ Workspace utils aliases ================"
echo "pyenv      -> Crea y activa entorno virtual Python, instala requirements.txt si existe."
echo "nenv       -> Instala dependencias npm/yarn y ejecuta build/test si hay package.json."
echo "dockup     -> Lanza docker-compose up si existe docker-compose.yml."
echo "ports      -> Muestra puertos abiertos y procesos asociados."
echo "kport      -> Mata el proceso que usa un puerto específico."
echo "openp      -> Abre el proyecto en VS Code."
echo "lint       -> Ejecuta linters sobre todo el workspace."
echo "bigf       -> Lista archivos grandes en el proyecto."
echo "bkup       -> Hace backup comprimido del workspace actual."
echo ""
echo "==================== Git utils aliases =================="
echo "gfix       -> Fixes issues with pull, merge, and rebase."
echo "gsub       -> Initializes and updates Git submodules."
echo "gpull      -> Pulls from all repositories."
echo "gpush      -> Pushes to all repositories."
echo "gtree      -> Displays the commit history as a tree."
echo "ginfo      -> Shows this information."
echo "gpurge     -> Uninstalls all Git utils and removes aliases."
echo "gclone     -> Clones all public repositories from a GitHub user."
echo "gclean     -> Deletes all cloned git repositories."
echo "gsta       -> Muestra el estado de todos los repositorios en subcarpetas."
echo "gcheck     -> Cambia a un commit específico (por hash o número) o muestra la lista numerada de commits si no se pasa argumento."
echo "gbrc       -> Borra ramas locales ya fusionadas/remotas eliminadas."
echo "gstsh      -> Aplica git stash en todos los repositorios."
echo "glogf      -> Busca una palabra en los logs de todos los repos."
echo "gstat      -> Muestra estadísticas de contribución por usuario."
echo "gundo      -> Recupera archivos borrados recientemente."
echo "gtag       -> Crea un tag de release y lo sube al remoto."
echo ""
echo "=================== Neovim utils aliases ================"
echo "snvim      -> Instala Neovim sin plugins."
echo "snvimp     -> Instala plugins y configuración avanzada de Neovim."
echo "snvima     -> Instala Neovim y plugins."
echo "senv       -> Instala Neovim, plugins y hace pull de todos los repos."
echo ""
echo "You can run any alias by simply typing it in the terminal."
echo "Contact: ismhernaismherna@student.42madrid.com"
